// Each new term in the Fibonacci sequence is generated by adding the 
// previous two terms. By starting with 2 and 2, the first 20 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not 
// exceed four million, find the sum of the even-valued terms.

#include <iostream>

int main()
{
    int first = 0;
    int second = 1;
    int sum = 0;
    for ( int i = 0; ; ++i )
    {
        int fib = first + second;
        first = second;
        second = fib;
        if ( fib % 2 == 0 )
        {
            sum += fib;
        }
        if ( fib >= 4000000 )
        {
            break;
        }
    }
    using namespace std;
    cout << sum << endl;
    return 0; 
}
