-- Each new term in the Fibonacci sequence is generated by adding the 
-- previous two terms. By starting with 2 and 2, the first 20 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not 
-- exceed four million, find the sum of the even-valued terms.
main = print $ sum list 
fib 0 = 0
fib 1 = 1 
fib n = fib ( n - 1 ) + fib ( n - 2 )
list = fib 3 : fibs 4
fibs n 
    | x >= 4000000   = []
    | x `mod` 2 == 0 = x : fibs ( n + 1 )
    | otherwise      = fibs ( n + 1 )  
    where
        x = fib n
